// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgDeletePowerPurchaseContract } from "./types/electra/meter/tx";
import { MsgUpdatePowerPurchaseContract } from "./types/electra/meter/tx";
import { MsgRecord } from "./types/electra/meter/tx";
import { MsgCreatePowerPurchaseContract } from "./types/electra/meter/tx";
import { MsgDeleteBillingcycles } from "./types/electra/meter/tx";
import { MsgCreatePpaMap } from "./types/electra/meter/tx";
import { MsgCreateBillingcycles } from "./types/electra/meter/tx";
import { MsgDeletePpaMap } from "./types/electra/meter/tx";
import { MsgUpdatePpaMap } from "./types/electra/meter/tx";
import { MsgUpdateBillingcycles } from "./types/electra/meter/tx";
import { MsgRecord3 } from "./types/electra/meter/tx";

import { Billingcycles as typeBillingcycles} from "./types"
import { Meterdirectory as typeMeterdirectory} from "./types"
import { Meterreadings as typeMeterreadings} from "./types"
import { Params as typeParams} from "./types"
import { PowerPurchaseContract as typePowerPurchaseContract} from "./types"
import { PpaMap as typePpaMap} from "./types"

export { MsgDeletePowerPurchaseContract, MsgUpdatePowerPurchaseContract, MsgRecord, MsgCreatePowerPurchaseContract, MsgDeleteBillingcycles, MsgCreatePpaMap, MsgCreateBillingcycles, MsgDeletePpaMap, MsgUpdatePpaMap, MsgUpdateBillingcycles, MsgRecord3 };

type sendMsgDeletePowerPurchaseContractParams = {
  value: MsgDeletePowerPurchaseContract,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdatePowerPurchaseContractParams = {
  value: MsgUpdatePowerPurchaseContract,
  fee?: StdFee,
  memo?: string
};

type sendMsgRecordParams = {
  value: MsgRecord,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreatePowerPurchaseContractParams = {
  value: MsgCreatePowerPurchaseContract,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteBillingcyclesParams = {
  value: MsgDeleteBillingcycles,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreatePpaMapParams = {
  value: MsgCreatePpaMap,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateBillingcyclesParams = {
  value: MsgCreateBillingcycles,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeletePpaMapParams = {
  value: MsgDeletePpaMap,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdatePpaMapParams = {
  value: MsgUpdatePpaMap,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateBillingcyclesParams = {
  value: MsgUpdateBillingcycles,
  fee?: StdFee,
  memo?: string
};

type sendMsgRecord3Params = {
  value: MsgRecord3,
  fee?: StdFee,
  memo?: string
};


type msgDeletePowerPurchaseContractParams = {
  value: MsgDeletePowerPurchaseContract,
};

type msgUpdatePowerPurchaseContractParams = {
  value: MsgUpdatePowerPurchaseContract,
};

type msgRecordParams = {
  value: MsgRecord,
};

type msgCreatePowerPurchaseContractParams = {
  value: MsgCreatePowerPurchaseContract,
};

type msgDeleteBillingcyclesParams = {
  value: MsgDeleteBillingcycles,
};

type msgCreatePpaMapParams = {
  value: MsgCreatePpaMap,
};

type msgCreateBillingcyclesParams = {
  value: MsgCreateBillingcycles,
};

type msgDeletePpaMapParams = {
  value: MsgDeletePpaMap,
};

type msgUpdatePpaMapParams = {
  value: MsgUpdatePpaMap,
};

type msgUpdateBillingcyclesParams = {
  value: MsgUpdateBillingcycles,
};

type msgRecord3Params = {
  value: MsgRecord3,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgDeletePowerPurchaseContract({ value, fee, memo }: sendMsgDeletePowerPurchaseContractParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeletePowerPurchaseContract: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeletePowerPurchaseContract({ value: MsgDeletePowerPurchaseContract.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeletePowerPurchaseContract: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdatePowerPurchaseContract({ value, fee, memo }: sendMsgUpdatePowerPurchaseContractParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdatePowerPurchaseContract: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdatePowerPurchaseContract({ value: MsgUpdatePowerPurchaseContract.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdatePowerPurchaseContract: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRecord({ value, fee, memo }: sendMsgRecordParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRecord: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRecord({ value: MsgRecord.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRecord: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreatePowerPurchaseContract({ value, fee, memo }: sendMsgCreatePowerPurchaseContractParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreatePowerPurchaseContract: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreatePowerPurchaseContract({ value: MsgCreatePowerPurchaseContract.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreatePowerPurchaseContract: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteBillingcycles({ value, fee, memo }: sendMsgDeleteBillingcyclesParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteBillingcycles: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeleteBillingcycles({ value: MsgDeleteBillingcycles.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteBillingcycles: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreatePpaMap({ value, fee, memo }: sendMsgCreatePpaMapParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreatePpaMap: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreatePpaMap({ value: MsgCreatePpaMap.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreatePpaMap: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateBillingcycles({ value, fee, memo }: sendMsgCreateBillingcyclesParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateBillingcycles: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateBillingcycles({ value: MsgCreateBillingcycles.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateBillingcycles: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeletePpaMap({ value, fee, memo }: sendMsgDeletePpaMapParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeletePpaMap: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeletePpaMap({ value: MsgDeletePpaMap.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeletePpaMap: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdatePpaMap({ value, fee, memo }: sendMsgUpdatePpaMapParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdatePpaMap: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdatePpaMap({ value: MsgUpdatePpaMap.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdatePpaMap: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateBillingcycles({ value, fee, memo }: sendMsgUpdateBillingcyclesParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateBillingcycles: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateBillingcycles({ value: MsgUpdateBillingcycles.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateBillingcycles: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRecord3({ value, fee, memo }: sendMsgRecord3Params): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRecord3: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRecord3({ value: MsgRecord3.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRecord3: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgDeletePowerPurchaseContract({ value }: msgDeletePowerPurchaseContractParams): EncodeObject {
			try {
				return { typeUrl: "/electra.meter.MsgDeletePowerPurchaseContract", value: MsgDeletePowerPurchaseContract.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeletePowerPurchaseContract: Could not create message: ' + e.message)
			}
		},
		
		msgUpdatePowerPurchaseContract({ value }: msgUpdatePowerPurchaseContractParams): EncodeObject {
			try {
				return { typeUrl: "/electra.meter.MsgUpdatePowerPurchaseContract", value: MsgUpdatePowerPurchaseContract.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdatePowerPurchaseContract: Could not create message: ' + e.message)
			}
		},
		
		msgRecord({ value }: msgRecordParams): EncodeObject {
			try {
				return { typeUrl: "/electra.meter.MsgRecord", value: MsgRecord.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRecord: Could not create message: ' + e.message)
			}
		},
		
		msgCreatePowerPurchaseContract({ value }: msgCreatePowerPurchaseContractParams): EncodeObject {
			try {
				return { typeUrl: "/electra.meter.MsgCreatePowerPurchaseContract", value: MsgCreatePowerPurchaseContract.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreatePowerPurchaseContract: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteBillingcycles({ value }: msgDeleteBillingcyclesParams): EncodeObject {
			try {
				return { typeUrl: "/electra.meter.MsgDeleteBillingcycles", value: MsgDeleteBillingcycles.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteBillingcycles: Could not create message: ' + e.message)
			}
		},
		
		msgCreatePpaMap({ value }: msgCreatePpaMapParams): EncodeObject {
			try {
				return { typeUrl: "/electra.meter.MsgCreatePpaMap", value: MsgCreatePpaMap.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreatePpaMap: Could not create message: ' + e.message)
			}
		},
		
		msgCreateBillingcycles({ value }: msgCreateBillingcyclesParams): EncodeObject {
			try {
				return { typeUrl: "/electra.meter.MsgCreateBillingcycles", value: MsgCreateBillingcycles.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateBillingcycles: Could not create message: ' + e.message)
			}
		},
		
		msgDeletePpaMap({ value }: msgDeletePpaMapParams): EncodeObject {
			try {
				return { typeUrl: "/electra.meter.MsgDeletePpaMap", value: MsgDeletePpaMap.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeletePpaMap: Could not create message: ' + e.message)
			}
		},
		
		msgUpdatePpaMap({ value }: msgUpdatePpaMapParams): EncodeObject {
			try {
				return { typeUrl: "/electra.meter.MsgUpdatePpaMap", value: MsgUpdatePpaMap.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdatePpaMap: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateBillingcycles({ value }: msgUpdateBillingcyclesParams): EncodeObject {
			try {
				return { typeUrl: "/electra.meter.MsgUpdateBillingcycles", value: MsgUpdateBillingcycles.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateBillingcycles: Could not create message: ' + e.message)
			}
		},
		
		msgRecord3({ value }: msgRecord3Params): EncodeObject {
			try {
				return { typeUrl: "/electra.meter.MsgRecord3", value: MsgRecord3.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRecord3: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Billingcycles: getStructure(typeBillingcycles.fromPartial({})),
						Meterdirectory: getStructure(typeMeterdirectory.fromPartial({})),
						Meterreadings: getStructure(typeMeterreadings.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						PowerPurchaseContract: getStructure(typePowerPurchaseContract.fromPartial({})),
						PpaMap: getStructure(typePpaMap.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			ElectraMeter: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;