// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgDeletePoll } from "./types/electra/dao/tx";
import { MsgCreatePoll } from "./types/electra/dao/tx";
import { MsgUpdatePoll } from "./types/electra/dao/tx";

import { Membership as typeMembership} from "./types"
import { DaoPacketData as typeDaoPacketData} from "./types"
import { NoData as typeNoData} from "./types"
import { Params as typeParams} from "./types"
import { Poll as typePoll} from "./types"

export { MsgDeletePoll, MsgCreatePoll, MsgUpdatePoll };

type sendMsgDeletePollParams = {
  value: MsgDeletePoll,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreatePollParams = {
  value: MsgCreatePoll,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdatePollParams = {
  value: MsgUpdatePoll,
  fee?: StdFee,
  memo?: string
};


type msgDeletePollParams = {
  value: MsgDeletePoll,
};

type msgCreatePollParams = {
  value: MsgCreatePoll,
};

type msgUpdatePollParams = {
  value: MsgUpdatePoll,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgDeletePoll({ value, fee, memo }: sendMsgDeletePollParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeletePoll: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeletePoll({ value: MsgDeletePoll.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeletePoll: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreatePoll({ value, fee, memo }: sendMsgCreatePollParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreatePoll: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreatePoll({ value: MsgCreatePoll.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreatePoll: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdatePoll({ value, fee, memo }: sendMsgUpdatePollParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdatePoll: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdatePoll({ value: MsgUpdatePoll.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdatePoll: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgDeletePoll({ value }: msgDeletePollParams): EncodeObject {
			try {
				return { typeUrl: "/electra.dao.MsgDeletePoll", value: MsgDeletePoll.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeletePoll: Could not create message: ' + e.message)
			}
		},
		
		msgCreatePoll({ value }: msgCreatePollParams): EncodeObject {
			try {
				return { typeUrl: "/electra.dao.MsgCreatePoll", value: MsgCreatePoll.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreatePoll: Could not create message: ' + e.message)
			}
		},
		
		msgUpdatePoll({ value }: msgUpdatePollParams): EncodeObject {
			try {
				return { typeUrl: "/electra.dao.MsgUpdatePoll", value: MsgUpdatePoll.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdatePoll: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Membership: getStructure(typeMembership.fromPartial({})),
						DaoPacketData: getStructure(typeDaoPacketData.fromPartial({})),
						NoData: getStructure(typeNoData.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						Poll: getStructure(typePoll.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			ElectraDao: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;