// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: electra/meter/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_233f661d7643ff7a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_233f661d7643ff7a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetMeterreadingsRequest struct {
	DeviceID  string `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *QueryGetMeterreadingsRequest) Reset()         { *m = QueryGetMeterreadingsRequest{} }
func (m *QueryGetMeterreadingsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMeterreadingsRequest) ProtoMessage()    {}
func (*QueryGetMeterreadingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_233f661d7643ff7a, []int{2}
}
func (m *QueryGetMeterreadingsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMeterreadingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMeterreadingsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMeterreadingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMeterreadingsRequest.Merge(m, src)
}
func (m *QueryGetMeterreadingsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMeterreadingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMeterreadingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMeterreadingsRequest proto.InternalMessageInfo

func (m *QueryGetMeterreadingsRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *QueryGetMeterreadingsRequest) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type QueryGetMeterreadingsResponse struct {
	Meterreadings Meterreadings `protobuf:"bytes,1,opt,name=meterreadings,proto3" json:"meterreadings"`
}

func (m *QueryGetMeterreadingsResponse) Reset()         { *m = QueryGetMeterreadingsResponse{} }
func (m *QueryGetMeterreadingsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMeterreadingsResponse) ProtoMessage()    {}
func (*QueryGetMeterreadingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_233f661d7643ff7a, []int{3}
}
func (m *QueryGetMeterreadingsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMeterreadingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMeterreadingsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMeterreadingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMeterreadingsResponse.Merge(m, src)
}
func (m *QueryGetMeterreadingsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMeterreadingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMeterreadingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMeterreadingsResponse proto.InternalMessageInfo

func (m *QueryGetMeterreadingsResponse) GetMeterreadings() Meterreadings {
	if m != nil {
		return m.Meterreadings
	}
	return Meterreadings{}
}

type QueryAllMeterreadingsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMeterreadingsRequest) Reset()         { *m = QueryAllMeterreadingsRequest{} }
func (m *QueryAllMeterreadingsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllMeterreadingsRequest) ProtoMessage()    {}
func (*QueryAllMeterreadingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_233f661d7643ff7a, []int{4}
}
func (m *QueryAllMeterreadingsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMeterreadingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMeterreadingsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMeterreadingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMeterreadingsRequest.Merge(m, src)
}
func (m *QueryAllMeterreadingsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMeterreadingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMeterreadingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMeterreadingsRequest proto.InternalMessageInfo

func (m *QueryAllMeterreadingsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllMeterreadingsResponse struct {
	Meterreadings []Meterreadings     `protobuf:"bytes,1,rep,name=meterreadings,proto3" json:"meterreadings"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMeterreadingsResponse) Reset()         { *m = QueryAllMeterreadingsResponse{} }
func (m *QueryAllMeterreadingsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllMeterreadingsResponse) ProtoMessage()    {}
func (*QueryAllMeterreadingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_233f661d7643ff7a, []int{5}
}
func (m *QueryAllMeterreadingsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMeterreadingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMeterreadingsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMeterreadingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMeterreadingsResponse.Merge(m, src)
}
func (m *QueryAllMeterreadingsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMeterreadingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMeterreadingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMeterreadingsResponse proto.InternalMessageInfo

func (m *QueryAllMeterreadingsResponse) GetMeterreadings() []Meterreadings {
	if m != nil {
		return m.Meterreadings
	}
	return nil
}

func (m *QueryAllMeterreadingsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetMeterdirectoryRequest struct {
	DeviceID      string `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Barcodeserial string `protobuf:"bytes,2,opt,name=barcodeserial,proto3" json:"barcodeserial,omitempty"`
}

func (m *QueryGetMeterdirectoryRequest) Reset()         { *m = QueryGetMeterdirectoryRequest{} }
func (m *QueryGetMeterdirectoryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMeterdirectoryRequest) ProtoMessage()    {}
func (*QueryGetMeterdirectoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_233f661d7643ff7a, []int{6}
}
func (m *QueryGetMeterdirectoryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMeterdirectoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMeterdirectoryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMeterdirectoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMeterdirectoryRequest.Merge(m, src)
}
func (m *QueryGetMeterdirectoryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMeterdirectoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMeterdirectoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMeterdirectoryRequest proto.InternalMessageInfo

func (m *QueryGetMeterdirectoryRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *QueryGetMeterdirectoryRequest) GetBarcodeserial() string {
	if m != nil {
		return m.Barcodeserial
	}
	return ""
}

type QueryGetMeterdirectoryResponse struct {
	Meterdirectory Meterdirectory `protobuf:"bytes,1,opt,name=meterdirectory,proto3" json:"meterdirectory"`
}

func (m *QueryGetMeterdirectoryResponse) Reset()         { *m = QueryGetMeterdirectoryResponse{} }
func (m *QueryGetMeterdirectoryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMeterdirectoryResponse) ProtoMessage()    {}
func (*QueryGetMeterdirectoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_233f661d7643ff7a, []int{7}
}
func (m *QueryGetMeterdirectoryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMeterdirectoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMeterdirectoryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMeterdirectoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMeterdirectoryResponse.Merge(m, src)
}
func (m *QueryGetMeterdirectoryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMeterdirectoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMeterdirectoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMeterdirectoryResponse proto.InternalMessageInfo

func (m *QueryGetMeterdirectoryResponse) GetMeterdirectory() Meterdirectory {
	if m != nil {
		return m.Meterdirectory
	}
	return Meterdirectory{}
}

type QueryAllMeterdirectoryRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMeterdirectoryRequest) Reset()         { *m = QueryAllMeterdirectoryRequest{} }
func (m *QueryAllMeterdirectoryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllMeterdirectoryRequest) ProtoMessage()    {}
func (*QueryAllMeterdirectoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_233f661d7643ff7a, []int{8}
}
func (m *QueryAllMeterdirectoryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMeterdirectoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMeterdirectoryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMeterdirectoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMeterdirectoryRequest.Merge(m, src)
}
func (m *QueryAllMeterdirectoryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMeterdirectoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMeterdirectoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMeterdirectoryRequest proto.InternalMessageInfo

func (m *QueryAllMeterdirectoryRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllMeterdirectoryResponse struct {
	Meterdirectory []Meterdirectory    `protobuf:"bytes,1,rep,name=meterdirectory,proto3" json:"meterdirectory"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMeterdirectoryResponse) Reset()         { *m = QueryAllMeterdirectoryResponse{} }
func (m *QueryAllMeterdirectoryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllMeterdirectoryResponse) ProtoMessage()    {}
func (*QueryAllMeterdirectoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_233f661d7643ff7a, []int{9}
}
func (m *QueryAllMeterdirectoryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMeterdirectoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMeterdirectoryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMeterdirectoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMeterdirectoryResponse.Merge(m, src)
}
func (m *QueryAllMeterdirectoryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMeterdirectoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMeterdirectoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMeterdirectoryResponse proto.InternalMessageInfo

func (m *QueryAllMeterdirectoryResponse) GetMeterdirectory() []Meterdirectory {
	if m != nil {
		return m.Meterdirectory
	}
	return nil
}

func (m *QueryAllMeterdirectoryResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "electra.meter.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "electra.meter.QueryParamsResponse")
	proto.RegisterType((*QueryGetMeterreadingsRequest)(nil), "electra.meter.QueryGetMeterreadingsRequest")
	proto.RegisterType((*QueryGetMeterreadingsResponse)(nil), "electra.meter.QueryGetMeterreadingsResponse")
	proto.RegisterType((*QueryAllMeterreadingsRequest)(nil), "electra.meter.QueryAllMeterreadingsRequest")
	proto.RegisterType((*QueryAllMeterreadingsResponse)(nil), "electra.meter.QueryAllMeterreadingsResponse")
	proto.RegisterType((*QueryGetMeterdirectoryRequest)(nil), "electra.meter.QueryGetMeterdirectoryRequest")
	proto.RegisterType((*QueryGetMeterdirectoryResponse)(nil), "electra.meter.QueryGetMeterdirectoryResponse")
	proto.RegisterType((*QueryAllMeterdirectoryRequest)(nil), "electra.meter.QueryAllMeterdirectoryRequest")
	proto.RegisterType((*QueryAllMeterdirectoryResponse)(nil), "electra.meter.QueryAllMeterdirectoryResponse")
}

func init() { proto.RegisterFile("electra/meter/query.proto", fileDescriptor_233f661d7643ff7a) }

var fileDescriptor_233f661d7643ff7a = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4d, 0x6b, 0x13, 0x41,
	0x18, 0xc7, 0x33, 0x69, 0x0d, 0x66, 0x24, 0x45, 0xc7, 0x06, 0xeb, 0x92, 0x6c, 0xdb, 0xa1, 0x6a,
	0xf1, 0x65, 0x87, 0x36, 0x08, 0xa2, 0x17, 0x5b, 0xc4, 0xfa, 0x82, 0x50, 0xf7, 0x24, 0xde, 0x26,
	0xc9, 0xb8, 0x2c, 0xec, 0xee, 0x6c, 0x77, 0xa7, 0xc5, 0x52, 0x72, 0xd1, 0x2f, 0x20, 0xf4, 0xe0,
	0x47, 0xf0, 0x28, 0x78, 0xf0, 0x33, 0xf4, 0x58, 0xf0, 0xe2, 0x49, 0x24, 0xf1, 0x83, 0x48, 0x66,
	0x27, 0x69, 0x67, 0xb3, 0xbb, 0x0d, 0xa5, 0x97, 0xd2, 0xcc, 0xfc, 0x9f, 0xe7, 0xf9, 0x3d, 0x2f,
	0xf3, 0x2c, 0xbc, 0xc9, 0x3c, 0xd6, 0x11, 0x11, 0x25, 0x3e, 0x13, 0x2c, 0x22, 0x3b, 0xbb, 0x2c,
	0xda, 0xb7, 0xc2, 0x88, 0x0b, 0x8e, 0x6a, 0xea, 0xca, 0x92, 0x57, 0xc6, 0xbc, 0xc3, 0x1d, 0x2e,
	0x6f, 0xc8, 0xf0, 0xbf, 0x44, 0x64, 0x34, 0x1c, 0xce, 0x1d, 0x8f, 0x11, 0x1a, 0xba, 0x84, 0x06,
	0x01, 0x17, 0x54, 0xb8, 0x3c, 0x88, 0xd5, 0xed, 0xdd, 0x0e, 0x8f, 0x7d, 0x1e, 0x93, 0x36, 0x8d,
	0x59, 0xe2, 0x9b, 0xec, 0xad, 0xb5, 0x99, 0xa0, 0x6b, 0x24, 0xa4, 0x8e, 0x1b, 0x48, 0xb1, 0xd2,
	0x1a, 0x3a, 0x49, 0x48, 0x23, 0xea, 0x8f, 0xfc, 0x2c, 0xeb, 0x77, 0xf2, 0x6f, 0xc4, 0x68, 0xd7,
	0x0d, 0x9c, 0x91, 0x04, 0x67, 0x48, 0xba, 0x6e, 0xc4, 0x3a, 0x82, 0x8f, 0x32, 0xc2, 0xf3, 0x10,
	0xbd, 0x1d, 0x42, 0x6c, 0x4b, 0xdf, 0x36, 0xdb, 0xd9, 0x65, 0xb1, 0xc0, 0xaf, 0xe0, 0x75, 0xed,
	0x34, 0x0e, 0x79, 0x10, 0x33, 0xd4, 0x82, 0x95, 0x84, 0x61, 0x01, 0x2c, 0x81, 0xd5, 0x2b, 0xeb,
	0x75, 0x4b, 0xab, 0x87, 0x95, 0xc8, 0x37, 0x67, 0x8f, 0xfe, 0x2c, 0x96, 0x6c, 0x25, 0xc5, 0xef,
	0x60, 0x43, 0xfa, 0xda, 0x62, 0xe2, 0xcd, 0x69, 0x48, 0x15, 0x0b, 0x19, 0xf0, 0x72, 0x97, 0xed,
	0xb9, 0x1d, 0xf6, 0xf2, 0x99, 0x74, 0x5b, 0xb5, 0xc7, 0xbf, 0x51, 0x03, 0x56, 0x85, 0xeb, 0xb3,
	0x58, 0x50, 0x3f, 0x5c, 0x28, 0x2f, 0x81, 0xd5, 0x59, 0xfb, 0xe4, 0x00, 0xbb, 0xb0, 0x99, 0xe3,
	0x59, 0xf1, 0xbe, 0x80, 0x35, 0xad, 0x2e, 0x0a, 0xbb, 0x91, 0xc2, 0xd6, 0x8c, 0x15, 0xbd, 0x6e,
	0x88, 0x3f, 0xa8, 0x24, 0x36, 0x3c, 0x2f, 0x33, 0x89, 0xe7, 0x10, 0x9e, 0x74, 0x4f, 0x85, 0xb9,
	0x6d, 0x25, 0xad, 0xb6, 0x86, 0xad, 0xb6, 0x92, 0x31, 0x52, 0xad, 0xb6, 0xb6, 0xa9, 0xc3, 0x94,
	0xad, 0x7d, 0xca, 0x12, 0xff, 0x00, 0x2a, 0xa7, 0xc9, 0x40, 0xf9, 0x39, 0xcd, 0x9c, 0x2b, 0x27,
	0xb4, 0xa5, 0x31, 0x97, 0x25, 0xf3, 0x9d, 0x33, 0x99, 0x13, 0x0c, 0x0d, 0x9a, 0xa6, 0xfa, 0x30,
	0x9e, 0xb1, 0x69, 0x5a, 0xbc, 0x02, 0x6b, 0x6d, 0x1a, 0x75, 0x78, 0x97, 0xc5, 0x2c, 0x72, 0xa9,
	0x27, 0x41, 0xaa, 0xb6, 0x7e, 0x88, 0x7d, 0x68, 0xe6, 0x85, 0x50, 0x75, 0x79, 0x0d, 0xe7, 0xf4,
	0x01, 0x57, 0x5d, 0x68, 0x66, 0x15, 0x66, 0x2c, 0x52, 0x95, 0x49, 0x99, 0x62, 0x27, 0xd5, 0x85,
	0x89, 0x8c, 0x2e, 0xaa, 0xdf, 0x3f, 0x81, 0x4a, 0x2c, 0x23, 0x52, 0x41, 0x62, 0x33, 0xe7, 0x4c,
	0xec, 0xc2, 0x7a, 0xbe, 0xfe, 0xb9, 0x02, 0x2f, 0x49, 0x70, 0x14, 0xc0, 0x4a, 0xf2, 0xee, 0xd1,
	0x72, 0x8a, 0x68, 0x72, 0xb1, 0x18, 0xb8, 0x48, 0x92, 0x84, 0xc1, 0xcd, 0x4f, 0xbf, 0xfe, 0x1d,
	0x96, 0x6f, 0xa0, 0x3a, 0xc9, 0x5a, 0x7f, 0xe8, 0x1b, 0x80, 0x35, 0x6d, 0xba, 0xd1, 0xbd, 0x2c,
	0xa7, 0x39, 0xeb, 0xc6, 0xb8, 0x3f, 0x9d, 0x58, 0xb1, 0x3c, 0x91, 0x2c, 0x0f, 0x51, 0x8b, 0x14,
	0xac, 0x5b, 0x72, 0x30, 0x9a, 0xe6, 0x1e, 0x39, 0x18, 0xaf, 0xa7, 0x1e, 0x3a, 0x04, 0xf0, 0xaa,
	0xe6, 0x76, 0xc3, 0xf3, 0xb2, 0x61, 0x73, 0xd6, 0x4a, 0x36, 0x6c, 0xde, 0x6a, 0xc0, 0x2b, 0x12,
	0xd6, 0x44, 0x8d, 0x22, 0x58, 0xf4, 0x1d, 0xc0, 0x39, 0x7d, 0x56, 0x50, 0x61, 0x4d, 0xd2, 0xb3,
	0x6f, 0x3c, 0x98, 0x52, 0xad, 0xa8, 0x9e, 0x4a, 0xaa, 0xc7, 0xe8, 0x11, 0x29, 0xfa, 0x1c, 0x69,
	0x35, 0xd4, 0xde, 0x7e, 0x0f, 0x7d, 0x05, 0xf0, 0x9a, 0xee, 0x7c, 0x58, 0xc8, 0xc2, 0xda, 0x4c,
	0x07, 0x9d, 0xfb, 0xe8, 0xf0, 0x2d, 0x09, 0xbd, 0x88, 0x9a, 0x85, 0xd0, 0x9b, 0xe4, 0xa8, 0x6f,
	0x82, 0xe3, 0xbe, 0x09, 0xfe, 0xf6, 0x4d, 0xf0, 0x65, 0x60, 0x96, 0x8e, 0x07, 0x66, 0xe9, 0xf7,
	0xc0, 0x2c, 0xbd, 0xaf, 0x8f, 0xec, 0x3e, 0x2a, 0x4b, 0xb1, 0x1f, 0xb2, 0xb8, 0x5d, 0x91, 0x5f,
	0xdd, 0xd6, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x44, 0x39, 0x2b, 0x64, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Meterreadings items.
	Meterreadings(ctx context.Context, in *QueryGetMeterreadingsRequest, opts ...grpc.CallOption) (*QueryGetMeterreadingsResponse, error)
	MeterreadingsAll(ctx context.Context, in *QueryAllMeterreadingsRequest, opts ...grpc.CallOption) (*QueryAllMeterreadingsResponse, error)
	// Queries a list of Meterdirectory items.
	Meterdirectory(ctx context.Context, in *QueryGetMeterdirectoryRequest, opts ...grpc.CallOption) (*QueryGetMeterdirectoryResponse, error)
	MeterdirectoryAll(ctx context.Context, in *QueryAllMeterdirectoryRequest, opts ...grpc.CallOption) (*QueryAllMeterdirectoryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/electra.meter.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Meterreadings(ctx context.Context, in *QueryGetMeterreadingsRequest, opts ...grpc.CallOption) (*QueryGetMeterreadingsResponse, error) {
	out := new(QueryGetMeterreadingsResponse)
	err := c.cc.Invoke(ctx, "/electra.meter.Query/Meterreadings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MeterreadingsAll(ctx context.Context, in *QueryAllMeterreadingsRequest, opts ...grpc.CallOption) (*QueryAllMeterreadingsResponse, error) {
	out := new(QueryAllMeterreadingsResponse)
	err := c.cc.Invoke(ctx, "/electra.meter.Query/MeterreadingsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Meterdirectory(ctx context.Context, in *QueryGetMeterdirectoryRequest, opts ...grpc.CallOption) (*QueryGetMeterdirectoryResponse, error) {
	out := new(QueryGetMeterdirectoryResponse)
	err := c.cc.Invoke(ctx, "/electra.meter.Query/Meterdirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MeterdirectoryAll(ctx context.Context, in *QueryAllMeterdirectoryRequest, opts ...grpc.CallOption) (*QueryAllMeterdirectoryResponse, error) {
	out := new(QueryAllMeterdirectoryResponse)
	err := c.cc.Invoke(ctx, "/electra.meter.Query/MeterdirectoryAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Meterreadings items.
	Meterreadings(context.Context, *QueryGetMeterreadingsRequest) (*QueryGetMeterreadingsResponse, error)
	MeterreadingsAll(context.Context, *QueryAllMeterreadingsRequest) (*QueryAllMeterreadingsResponse, error)
	// Queries a list of Meterdirectory items.
	Meterdirectory(context.Context, *QueryGetMeterdirectoryRequest) (*QueryGetMeterdirectoryResponse, error)
	MeterdirectoryAll(context.Context, *QueryAllMeterdirectoryRequest) (*QueryAllMeterdirectoryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Meterreadings(ctx context.Context, req *QueryGetMeterreadingsRequest) (*QueryGetMeterreadingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Meterreadings not implemented")
}
func (*UnimplementedQueryServer) MeterreadingsAll(ctx context.Context, req *QueryAllMeterreadingsRequest) (*QueryAllMeterreadingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MeterreadingsAll not implemented")
}
func (*UnimplementedQueryServer) Meterdirectory(ctx context.Context, req *QueryGetMeterdirectoryRequest) (*QueryGetMeterdirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Meterdirectory not implemented")
}
func (*UnimplementedQueryServer) MeterdirectoryAll(ctx context.Context, req *QueryAllMeterdirectoryRequest) (*QueryAllMeterdirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MeterdirectoryAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/electra.meter.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Meterreadings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMeterreadingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Meterreadings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/electra.meter.Query/Meterreadings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Meterreadings(ctx, req.(*QueryGetMeterreadingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MeterreadingsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMeterreadingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MeterreadingsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/electra.meter.Query/MeterreadingsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MeterreadingsAll(ctx, req.(*QueryAllMeterreadingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Meterdirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMeterdirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Meterdirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/electra.meter.Query/Meterdirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Meterdirectory(ctx, req.(*QueryGetMeterdirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MeterdirectoryAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMeterdirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MeterdirectoryAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/electra.meter.Query/MeterdirectoryAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MeterdirectoryAll(ctx, req.(*QueryAllMeterdirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "electra.meter.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Meterreadings",
			Handler:    _Query_Meterreadings_Handler,
		},
		{
			MethodName: "MeterreadingsAll",
			Handler:    _Query_MeterreadingsAll_Handler,
		},
		{
			MethodName: "Meterdirectory",
			Handler:    _Query_Meterdirectory_Handler,
		},
		{
			MethodName: "MeterdirectoryAll",
			Handler:    _Query_MeterdirectoryAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "electra/meter/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetMeterreadingsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMeterreadingsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMeterreadingsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x10
	}
	if len(m.DeviceID) > 0 {
		i -= len(m.DeviceID)
		copy(dAtA[i:], m.DeviceID)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DeviceID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMeterreadingsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMeterreadingsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMeterreadingsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Meterreadings.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllMeterreadingsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMeterreadingsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMeterreadingsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMeterreadingsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMeterreadingsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMeterreadingsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Meterreadings) > 0 {
		for iNdEx := len(m.Meterreadings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Meterreadings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMeterdirectoryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMeterdirectoryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMeterdirectoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Barcodeserial) > 0 {
		i -= len(m.Barcodeserial)
		copy(dAtA[i:], m.Barcodeserial)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Barcodeserial)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DeviceID) > 0 {
		i -= len(m.DeviceID)
		copy(dAtA[i:], m.DeviceID)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DeviceID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMeterdirectoryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMeterdirectoryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMeterdirectoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Meterdirectory.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllMeterdirectoryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMeterdirectoryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMeterdirectoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMeterdirectoryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMeterdirectoryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMeterdirectoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Meterdirectory) > 0 {
		for iNdEx := len(m.Meterdirectory) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Meterdirectory[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetMeterreadingsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DeviceID)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovQuery(uint64(m.Timestamp))
	}
	return n
}

func (m *QueryGetMeterreadingsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Meterreadings.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllMeterreadingsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMeterreadingsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Meterreadings) > 0 {
		for _, e := range m.Meterreadings {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetMeterdirectoryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DeviceID)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Barcodeserial)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetMeterdirectoryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Meterdirectory.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllMeterdirectoryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMeterdirectoryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Meterdirectory) > 0 {
		for _, e := range m.Meterdirectory {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMeterreadingsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMeterreadingsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMeterreadingsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMeterreadingsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMeterreadingsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMeterreadingsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meterreadings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Meterreadings.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMeterreadingsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMeterreadingsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMeterreadingsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMeterreadingsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMeterreadingsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMeterreadingsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meterreadings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Meterreadings = append(m.Meterreadings, Meterreadings{})
			if err := m.Meterreadings[len(m.Meterreadings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMeterdirectoryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMeterdirectoryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMeterdirectoryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Barcodeserial", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Barcodeserial = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMeterdirectoryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMeterdirectoryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMeterdirectoryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meterdirectory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Meterdirectory.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMeterdirectoryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMeterdirectoryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMeterdirectoryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMeterdirectoryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMeterdirectoryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMeterdirectoryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meterdirectory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Meterdirectory = append(m.Meterdirectory, Meterdirectory{})
			if err := m.Meterdirectory[len(m.Meterdirectory)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
